version: '3.8'

services:
  web:
    build: .
    container_name: process_monitoring_web
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=process_monitoring.settings
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/available-host/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
